### ISSUE TITLE
rogue missiles with enemy disabled

### ISSUE THREAD

**Issue by d0rfl** [factropy/community#38]
From discord: report of missiles arriving despite enemy checkbox disabled.

Bit unclear, but it may be related to loading a save game, so check whether the flag persists and is restored in time to prevent an attack.

**Comment by timspeedle** [comment]
On the tick when the missiles would detonate, what if they were to re-check the existing setting of if the enemies are enabled in the game or not?  If enemies are not enabled, they can just delete themselves without exploding?
